"""Sample catalog for demos: 21 artisan stores and 36 listings across six craft categories.

Every listing uses a licensed Pexels photograph (credits in docs/storefront-images.md).
The stores and people are illustrative sample data, not real sellers. No ratings,
reviews or orders are generated. Seeded rows are tagged so they can be removed with
`python -m backend.scripts.seed_catalog --remove`.
"""

MAKERS = {
    "kanchi": ("Meenakshi Sundaram", "Kanchi Pattu Weaves", "Kanchipuram, Tamil Nadu", "Handloom & Textiles", "Tamil", "631501"),
    "sanganer": ("Hemraj Chhipa", "Sanganer Chhapai Studio", "Sanganer, Rajasthan", "Handloom & Textiles", "Hindi", "302029"),
    "kullu": ("Devki Thakur", "Kullu Valley Looms", "Kullu, Himachal Pradesh", "Handloom & Textiles", "Hindi", "175101"),
    "bhujodi": ("Hiraben Vankar", "Bhujodi Needlecraft", "Bhuj, Gujarat", "Handloom & Textiles", "Gujarati", "370020"),
    "chinar": ("Shabnam Akhtar", "Chinar Crewel House", "Srinagar, Jammu & Kashmir", "Handloom & Textiles", "Kashmiri", "190001"),
    "mithila": ("Sunita Jha", "Mithila Rang", "Madhubani, Bihar", "Traditional Paintings", "Hindi", "847211"),
    "neelkala": ("Gopal Prajapat", "Neel Kala Blue Pottery", "Jaipur, Rajasthan", "Pottery & Ceramics", "Hindi", "302002"),
    "mittighar": ("Kamla Devi", "Mitti Ghar Pottery", "Khurja, Uttar Pradesh", "Pottery & Ceramics", "Hindi", "203131"),
    "dahanu": ("Lakshmi Bhoir", "Dahanu Warli Collective", "Dahanu, Maharashtra", "Pottery & Ceramics", "Marathi", "401602"),
    "barpeta": ("Bipul Das", "Barpeta Cane Works", "Barpeta, Assam", "Cane & Bamboo", "Assamese", "781301"),
    "tripura": ("Rina Debbarma", "Tripura Bamboo Craft", "Agartala, Tripura", "Cane & Bamboo", "Bengali", "799001"),
    "khasi": ("Banteilang Syiem", "Khasi Hills Bamboo", "Shillong, Meghalaya", "Cane & Bamboo", "Khasi", "793001"),
    "channapatna": ("Venkatesh Gowda", "Channapatna Colours", "Channapatna, Karnataka", "Woodcraft & Carving", "Kannada", "562160"),
    "mysuru": ("Shivakumar Achar", "Mysuru Carvers", "Mysuru, Karnataka", "Woodcraft & Carving", "Kannada", "570001"),
    "saharanpur": ("Imran Qureshi", "Saharanpur Wood Art", "Saharanpur, Uttar Pradesh", "Woodcraft & Carving", "Hindi", "247001"),
    "bastar": ("Sukhchand Baghel", "Bastar Dhokra Shilp", "Kondagaon, Chhattisgarh", "Metal Craft & Bell Metal", "Hindi", "494226"),
    "moradabad": ("Farhan Ansari", "Moradabad Brass House", "Moradabad, Uttar Pradesh", "Metal Craft & Bell Metal", "Hindi", "244001"),
    "swamimalai": ("R. Raghavan", "Swamimalai Bronze Works", "Swamimalai, Tamil Nadu", "Metal Craft & Bell Metal", "Tamil", "612302"),
    "raghurajpur": ("Bhagyashree Mahapatra", "Raghurajpur Patta Art", "Raghurajpur, Odisha", "Traditional Paintings", "Odia", "752012"),
    "pingla": ("Swarna Chitrakar", "Pingla Patachitra", "Pingla, West Bengal", "Traditional Paintings", "Bengali", "721140"),
    "udaipur": ("Kavita Soni", "Udaipur Art Atelier", "Udaipur, Rajasthan", "Traditional Paintings", "Hindi", "313001"),
}

GI = "GI-tagged craft"

# crop: optional (left, top, right, bottom) fractions of the source photo.
# costs: (material, labour, packaging) in INR.
PRODUCTS = [
    # ── Handloom & Textiles ──────────────────────────────────────────
    dict(slug="kanchipuram-silk-saree", photo=10317127, maker="kanchi", category="Handloom & Textiles",
         name="Kanchipuram Pure Silk Saree with Zari Buttas", craft="Kanchipuram Silk Weaving",
         material="Pure mulberry silk with zari", color="Tangerine and violet", technique="Korvai handloom weaving",
         dimensions="6.2 m saree with 0.8 m blouse piece", weight="750 g", time="18 days",
         price=14500, costs=(7800, 3600, 250), stock=3, badge=GI, featured=True,
         short="A rich handwoven silk saree with repeating zari buttas, woven on a traditional pit loom.",
         desc="Woven over eighteen days on a pit loom in Kanchipuram, this saree pairs a glowing silk body with dense zari buttas that catch the light as you move. The korvai technique interlocks the border and body by hand, which is why a true Kanchi silk feels substantial and drapes crisply. It comes with an unstitched blouse piece.",
         specs=["Handwoven on a pit loom", "Unstitched 0.8 m blouse piece included", "Dry clean only"],
         hi=("बुट्टा ज़री वाली शुद्ध कांचीपुरम रेशमी साड़ी", "पारंपरिक गड्ढा-करघे पर हाथ से बुनी भारी रेशमी साड़ी, जिसमें ज़री के बुट्टे हैं।"),
         te=("జరీ బుట్టాలతో స్వచ్ఛమైన కంచిపట్టు చీర", "సంప్రదాయ మగ్గంపై చేతితో నేసిన బరువైన పట్టు చీర, జరీ బుట్టాలతో.")),
    dict(slug="sanganer-mandala-table-cover", photo=8751695, maker="sanganer", category="Handloom & Textiles",
         name="Hand Block-Printed Mandala Cotton Table Cover", craft="Sanganeri Hand Block Printing",
         material="Pure cotton", color="Ivory with vermilion and green", technique="Hand block printing",
         dimensions="152 × 229 cm (fits a 6-seater table)", weight="450 g", time="5 days",
         price=1850, costs=(520, 600, 80), stock=14, badge=GI,
         short="A soft cotton table cover printed by hand with a central mandala and geometric borders.",
         desc="Each colour on this table cover is stamped separately with carved teak blocks, so the mandala and borders carry the tiny, charming variations of hand printing. The cotton softens beautifully with every wash. Made in Sanganer, one of Rajasthan's oldest block-printing centres.",
         specs=["Printed with hand-carved wooden blocks", "Machine wash cold, dry in shade", "Colour may vary slightly between pieces"],
         hi=("हाथ से ब्लॉक-प्रिंट किया मंडला सूती टेबल कवर", "लकड़ी के ब्लॉक से हाथ से छपा मुलायम सूती टेबल कवर।"),
         te=("చేతి బ్లాక్ ప్రింట్ మండల కాటన్ టేబుల్ కవర్", "చెక్క బ్లాకులతో చేతితో ముద్రించిన మెత్తని కాటన్ టేబుల్ కవర్.")),
    dict(slug="kullu-wool-stole", photo=35170069, maker="kullu", category="Handloom & Textiles",
         name="Kullu Handwoven Striped Wool Stole", craft="Kullu Shawl Weaving",
         material="Sheep wool blend", color="Charcoal and ash grey", technique="Handloom weaving",
         dimensions="200 × 70 cm", weight="280 g", time="4 days",
         price=2400, costs=(850, 700, 60), stock=9, badge=GI,
         short="A warm, lightweight wool stole with classic stripes, woven on a handloom in the Kullu valley.",
         desc="Woven in the Kullu valley where winters are long, this stole balances warmth with an easy, light drape. The two-tone stripe works over a coat or with a kurta. Hand-finished fringes and a soft wool blend make it an everyday winter favourite.",
         specs=["Handloom woven", "Hand-knotted fringe ends", "Dry clean or gentle hand wash"],
         hi=("कुल्लू हाथ से बुना धारीदार ऊनी स्टोल", "कुल्लू घाटी में हथकरघे पर बुना गर्म और हल्का ऊनी स्टोल।"),
         te=("కుల్లు చేనేత చారల ఉన్ని స్టోల్", "కుల్లు లోయలో మగ్గంపై నేసిన వెచ్చని, తేలికైన ఉన్ని స్టోల్.")),
    dict(slug="kutch-elephant-table-runner", photo=37975931, maker="bhujodi", category="Handloom & Textiles",
         name="Kutch Hand-Embroidered Elephant Table Runner", craft="Kutch Embroidery",
         material="Cotton base with silk and cotton threads, mirrors", color="Maroon with ivory", technique="Hand embroidery with mirror work",
         dimensions="150 × 35 cm", weight="320 g", time="12 days",
         price=3200, costs=(650, 1600, 80), stock=5, badge=GI,
         short="A maroon table runner with a hand-embroidered elephant medallion and shimmering mirror work.",
         desc="The central elephant and the rows of mirrors on this runner are stitched entirely by hand by women embroiderers in Kutch. It takes close to two weeks to finish one piece. Lay it on a dining table or use it as a wall hanging.",
         specs=["Hand embroidered with mirror work", "Cotton backing", "Dry clean recommended"],
         hi=("कच्छ हाथ-कढ़ाई वाला हाथी टेबल रनर", "हाथ से कढ़ाई और शीशे के काम वाला कच्छ का टेबल रनर।"),
         te=("కచ్ చేతి ఎంబ్రాయిడరీ ఏనుగు టేబుల్ రన్నర్", "చేతి ఎంబ్రాయిడరీ, అద్దాల పనితో కచ్ టేబుల్ రన్నర్.")),
    dict(slug="madhubani-tussar-dupatta", photo=165891, maker="mithila", category="Handloom & Textiles",
         name="Madhubani Hand-Painted Tussar Silk Dupatta", craft="Madhubani Painting",
         material="Tussar silk", color="Natural beige with teal and rust", technique="Hand painted with fabric colours",
         dimensions="230 × 90 cm", weight="180 g", time="7 days",
         price=4200, costs=(1100, 1700, 60), stock=6, badge=GI, featured=True,
         short="A natural tussar silk dupatta with a hand-painted Madhubani fish border.",
         desc="Fish are a symbol of plenty in Mithila art, and here they swim along the border of a textured tussar silk dupatta. Every line is painted freehand, so no two dupattas are identical. The colours are heat-set to stay bright.",
         specs=["Hand painted, heat-set colours", "Natural tussar texture", "Dry clean only"],
         hi=("मधुबनी हाथ से पेंट किया तसर सिल्क दुपट्टा", "तसर सिल्क पर हाथ से बनी मधुबनी मछली बॉर्डर वाला दुपट्टा।"),
         te=("మధుబని చేతి చిత్రణ టస్సర్ పట్టు దుపట్టా", "టస్సర్ పట్టుపై చేతితో వేసిన మధుబని చేపల అంచు దుపట్టా.")),
    dict(slug="kashmiri-crewel-cushion-cover", photo=34887544, maker="chinar", category="Handloom & Textiles",
         name="Kashmiri Crewel-Embroidered Cushion Cover", craft="Kashmiri Crewel Embroidery",
         material="Cotton duck with wool crewel yarn", color="Ivory, cobalt and pomegranate red", technique="Aari chain-stitch embroidery",
         dimensions="40 × 40 cm, zip closure (insert not included)", weight="220 g", time="6 days",
         price=1450, costs=(320, 520, 50), stock=18,
         short="A bold cushion cover with pomegranate motifs worked in wool chain stitch.",
         desc="Crewel embroiderers in Srinagar use a hooked aari needle to lay thousands of tiny chain stitches in wool yarn. The raised, textured pomegranate pattern brings warmth to a sofa or reading chair. Finished with a concealed zip.",
         specs=["Hand embroidered with an aari hook", "Concealed zip", "Cushion insert not included"],
         hi=("कश्मीरी क्रूअल कढ़ाई वाला कुशन कवर", "ऊनी धागे की चेन-सिलाई वाला अनार डिज़ाइन कुशन कवर।"),
         te=("కాశ్మీరీ క్రూయెల్ ఎంబ్రాయిడరీ కుషన్ కవర్", "ఉన్ని దారంతో గొలుసు కుట్టు దానిమ్మ డిజైన్ కుషన్ కవర్.")),

    # ── Pottery & Ceramics ───────────────────────────────────────────
    dict(slug="jaipur-blue-pottery-surahi-vase", photo=20239419, maker="neelkala", category="Pottery & Ceramics",
         crop=(0.18, 0.28, 0.98, 0.95),
         name="Jaipur Blue Pottery Surahi Vase", craft="Jaipur Blue Pottery",
         material="Quartz powder, glass and multani mitti (no clay)", color="Cobalt blue and white", technique="Hand moulded, hand painted, low fired",
         dimensions="Height 30 cm, base 13 cm", weight="900 g", time="10 days",
         price=2850, costs=(520, 900, 180), stock=7, badge=GI, featured=True,
         short="A tall surahi-shaped vase hand-painted with cobalt floral work in the Jaipur blue pottery tradition.",
         desc="Jaipur blue pottery is unusual because it contains no clay: the body is made from quartz powder and glass, then painted with cobalt oxide and fired at a low temperature. This surahi's long neck and intricate floral bands make it a striking piece on a console or shelf.",
         specs=["Made without clay", "Hand painted with cobalt oxide", "Decorative use; wipe with a dry cloth"],
         hi=("जयपुर ब्लू पॉटरी सुराही फूलदान", "कोबाल्ट नीले फूलों से हाथ से रंगी जयपुर ब्लू पॉटरी सुराही।"),
         te=("జైపూర్ బ్లూ పాటరీ సురాహీ పూలకుండీ", "కోబాల్ట్ నీలి పూలతో చేతితో రంగులు వేసిన జైపూర్ సురాహీ.")),
    dict(slug="blue-pottery-circle-planter", photo=38108950, maker="neelkala", category="Pottery & Ceramics",
         name="Blue Pottery Circle-Motif Planter", craft="Jaipur Blue Pottery",
         material="Quartz powder, glass and multani mitti", color="Deep blue, cream and ochre", technique="Hand moulded and hand painted",
         dimensions="Height 14 cm, diameter 16 cm", weight="700 g", time="8 days",
         price=1650, costs=(260, 520, 140), stock=11, badge=GI,
         short="A glossy deep-blue planter ringed with hand-painted circles.",
         desc="A cheerful band of hand-painted circles wraps this deep-blue planter. It has no drainage hole, so use it as a cover pot for a small plant, or on its own to hold keys, fruit or trinkets.",
         specs=["No drainage hole (use as a cover pot)", "Hand painted glaze", "Wipe clean"],
         hi=("ब्लू पॉटरी गोल डिज़ाइन वाला गमला", "हाथ से बने गोल डिज़ाइन वाला चमकदार नीला गमला।"),
         te=("బ్లూ పాటరీ వృత్తాకార డిజైన్ మొక్కల కుండీ", "చేతితో వేసిన వృత్తాల డిజైన్‌తో మెరిసే నీలి కుండీ.")),
    dict(slug="warli-terracotta-planter", photo=11664431, maker="dahanu", category="Pottery & Ceramics",
         crop=(0.1, 0.28, 0.9, 0.85),
         name="Warli Hand-Painted Terracotta Planter", craft="Warli Painting",
         material="Terracotta", color="Earth brown with white and mint", technique="Wheel thrown, kiln fired, hand painted",
         dimensions="Height 12 cm, diameter 18 cm", weight="1.1 kg", time="6 days",
         price=890, costs=(110, 330, 90), stock=20, badge=GI,
         short="A terracotta planter painted with a ring of dancing Warli figures.",
         desc="Warli artists paint simple circles, triangles and lines to show village life, and this planter carries the famous tarpa dance around its rim. The terracotta breathes, which keeps plant roots healthy. Painted by hand in Dahanu.",
         specs=["Kiln-fired terracotta", "Hand painted Warli motifs", "Suitable for indoor plants"],
         hi=("वारली चित्रकारी वाला टेराकोटा गमला", "नाचती वारली आकृतियों से हाथ से रंगा टेराकोटा गमला।"),
         te=("వార్లీ చిత్రాలతో టెర్రకోట మొక్కల కుండీ", "నృత్యం చేసే వార్లీ బొమ్మలతో చేతితో వేసిన టెర్రకోట కుండీ.")),
    dict(slug="terracotta-diya-set-24", photo=39189948, maker="mittighar", category="Pottery & Ceramics",
         name="Handmade Terracotta Diya Set (Pack of 24)", craft="Terracotta Pottery",
         material="Natural river clay", color="Natural terracotta", technique="Hand pinched and kiln fired",
         dimensions="About 6 cm diameter each", weight="1.2 kg", time="3 days",
         price=399, costs=(40, 150, 45), stock=60,
         short="Two dozen classic clay diyas, shaped by hand and fired for Diwali and everyday puja.",
         desc="These unpainted diyas are shaped by hand from river clay and kiln fired, just as they have been for generations. Soak them in water for a few minutes before use so they absorb less oil. Perfect for Diwali, Karthigai Deepam or a quiet evening lamp.",
         specs=["Pack of 24", "Soak in water before first use", "Each diya is slightly unique"],
         hi=("हाथ से बने मिट्टी के दीये (24 का सेट)", "दिवाली और पूजा के लिए हाथ से बने मिट्टी के 24 दीये।"),
         te=("చేతితో చేసిన మట్టి దీపాలు (24 సెట్)", "దీపావళి, పూజ కోసం చేతితో చేసిన 24 మట్టి ప్రమిదలు.")),
    dict(slug="terracotta-bud-vase-trio", photo=30698565, maker="mittighar", category="Pottery & Ceramics",
         crop=(0.1, 0.22, 0.82, 0.9),
         name="Terracotta Bud Vase Set of 3", craft="Terracotta Pottery",
         material="Terracotta", color="Burnt orange", technique="Wheel thrown and burnished",
         dimensions="Heights 15, 18 and 22 cm", weight="1.4 kg", time="5 days",
         price=1200, costs=(150, 420, 110), stock=15,
         short="Three burnished terracotta bud vases in graduated heights.",
         desc="Thrown on the wheel and burnished to a soft sheen, these three vases look lovely grouped with dried grasses or a single stem each. The warm terracotta tone suits both modern and traditional rooms.",
         specs=["Set of 3", "Not waterproof inside; use with dried flowers or a glass insert", "Wipe with a dry cloth"],
         hi=("टेराकोटा फूलदान (3 का सेट)", "अलग-अलग ऊंचाई वाले तीन चमकाए हुए टेराकोटा फूलदान।"),
         te=("టెర్రకోట పూలకుండీలు (3 సెట్)", "వేర్వేరు ఎత్తుల్లో మెరుగుపెట్టిన మూడు టెర్రకోట పూలకుండీలు.")),
    dict(slug="khurja-stoneware-chai-cups", photo=28509629, maker="mittighar", category="Pottery & Ceramics",
         name="Glazed Stoneware Chai Cups (Set of 2)", craft="Khurja Pottery",
         material="Stoneware clay, lead-free food-safe glaze", color="Forest green with speckled cream", technique="Wheel thrown, reactive glaze, high fired",
         dimensions="180 ml each", weight="700 g", time="7 days",
         price=1100, costs=(190, 380, 90), stock=16,
         short="A pair of sturdy stoneware chai cups finished in a speckled green reactive glaze.",
         desc="Made in Khurja, India's best-known ceramic town, these cups are high fired so they are strong enough for daily chai. The reactive glaze pools differently on every piece, so your pair will have its own pattern.",
         specs=["Lead-free, food-safe glaze", "Microwave and dishwasher safe", "Set of 2"],
         hi=("ग्लेज़्ड स्टोनवेयर चाय कप (2 का सेट)", "खुर्जा में बने मज़बूत, हरे ग्लेज़ वाले दो चाय कप।"),
         te=("గ్లేజ్ స్టోన్‌వేర్ టీ కప్పులు (2 సెట్)", "ఖుర్జాలో చేసిన దృఢమైన ఆకుపచ్చ గ్లేజ్ టీ కప్పులు.")),

    # ── Cane & Bamboo ────────────────────────────────────────────────
    dict(slug="cane-cylinder-pendant-lamp", photo=3554241, maker="barpeta", category="Cane & Bamboo",
         crop=(0.0, 0.0, 0.62, 1.0),
         name="Handwoven Cane Cylinder Pendant Lamp", craft="Assam Cane Weaving",
         material="Split cane on a steel frame", color="Natural honey", technique="Hand-woven open weave",
         dimensions="30 cm diameter × 32 cm height, 1 m cord", weight="650 g", time="4 days",
         price=2300, costs=(480, 760, 160), stock=8, featured=True,
         short="A two-tier cane pendant that casts a soft, patterned glow.",
         desc="Split cane is woven around a light steel frame so the lamp keeps its shape for years. When lit, the open weave throws a gentle pattern across walls and ceiling. Comes with a 1 m cord and an E27 holder.",
         specs=["E27 holder, bulb not included", "1 m fabric cord", "Dust with a soft brush"],
         hi=("हाथ से बुना बेंत का सिलिंडर पेंडेंट लैंप", "मुलायम रोशनी देने वाला हाथ से बुना बेंत का लटकने वाला लैंप।"),
         te=("చేతితో అల్లిన బెత్తం సిలిండర్ వేలాడే దీపం", "మృదువైన వెలుగు ఇచ్చే చేతితో అల్లిన బెత్తం దీపం.")),
    dict(slug="bamboo-dome-pendant-lamp", photo=36721671, maker="tripura", category="Cane & Bamboo",
         name="Bamboo Dome Pendant Lamp Shade", craft="Tripura Bamboo Craft",
         material="Tripura bamboo strips", color="Warm natural", technique="Twill hand weaving",
         dimensions="45 cm diameter", weight="800 g", time="5 days",
         price=2750, costs=(420, 1000, 200), stock=6,
         short="A generous woven bamboo dome that brings warmth to dining and living spaces.",
         desc="Tripura's bamboo weavers split and shave bamboo into thin, flexible strips before weaving this rounded dome by hand. Hang it over a dining table for a warm, restaurant-style glow.",
         specs=["Fits standard E27 pendant kits", "Bulb and cord not included", "Keep away from moisture"],
         hi=("बांस का गुंबद आकार पेंडेंट लैंप शेड", "हाथ से बुना बांस का बड़ा गुंबद लैंप शेड।"),
         te=("వెదురు గుమ్మట ఆకార వేలాడే దీపపు షేడ్", "చేతితో అల్లిన పెద్ద వెదురు గుమ్మట దీపపు షేడ్.")),
    dict(slug="cane-round-serving-tray", photo=25286921, maker="barpeta", category="Cane & Bamboo",
         crop=(0.0, 0.42, 1.0, 1.0),
         name="Cane Round Serving Tray with Handles", craft="Assam Cane Weaving",
         material="Rattan cane", color="Walnut brown", technique="Coil weaving with lacquer finish",
         dimensions="40 cm diameter, 7 cm height", weight="900 g", time="3 days",
         price=1350, costs=(280, 450, 110), stock=12,
         short="A sturdy coil-woven cane tray with carved handles for tea, snacks or display.",
         desc="Thick rattan is coiled and stitched into a tray that is light but surprisingly strong. A clear lacquer finish protects the cane and makes it easy to wipe. Use it for serving chai, or as a catch-all on an ottoman.",
         specs=["Lacquer finish, wipe clean", "Not for hot pans", "Handwoven in Barpeta"],
         hi=("हैंडल वाली बेंत की गोल सर्विंग ट्रे", "चाय और नाश्ते के लिए मज़बूत हाथ से बुनी बेंत की ट्रे।"),
         te=("హ్యాండిల్స్‌తో బెత్తం గుండ్రని సర్వింగ్ ట్రే", "టీ, అల్పాహారం కోసం దృఢమైన చేతి అల్లిక బెత్తం ట్రే.")),
    dict(slug="bamboo-round-storage-baskets", photo=31047258, maker="tripura", category="Cane & Bamboo",
         crop=(0.1, 0.15, 0.95, 0.95),
         name="Bamboo Round Storage Baskets (Set of 2)", craft="Tripura Bamboo Craft",
         material="Bamboo", color="Natural", technique="Hexagonal hand weave",
         dimensions="28 cm and 24 cm diameter", weight="1 kg", time="4 days",
         price=1150, costs=(180, 460, 120), stock=10,
         short="Two rounded bamboo baskets for yarn, toys, laundry or plants.",
         desc="A tight hexagonal weave gives these baskets their rounded, lantern-like shape. They stack neatly and look good enough to leave out, whether they hold knitting, children's toys or a potted plant.",
         specs=["Set of 2", "Handwoven bamboo", "Keep dry"],
         hi=("बांस की गोल स्टोरेज टोकरियाँ (2 का सेट)", "सामान रखने के लिए बांस की दो गोल टोकरियाँ।"),
         te=("వెదురు గుండ్రని నిల్వ బుట్టలు (2 సెట్)", "సామాను నిల్వకు రెండు గుండ్రని వెదురు బుట్టలు.")),
    dict(slug="khasi-bamboo-carry-basket", photo=38037370, maker="khasi", category="Cane & Bamboo",
         crop=(0.12, 0.3, 0.9, 0.92),
         name="Khasi Bamboo Carry Basket (Khoh)", craft="Meghalaya Bamboo Craft",
         material="Bamboo with cane rim", color="Natural", technique="Hand woven, cane bound",
         dimensions="38 cm height, 34 cm top width", weight="700 g", time="3 days",
         price=950, costs=(120, 380, 110), stock=9,
         short="The traditional tapered basket carried in the Khasi hills, now a beautiful storage piece.",
         desc="In Meghalaya the khoh is carried on the back with a head strap to bring home firewood and vegetables. Its tapered shape and cane-bound rim make it strong and stable. At home it works as a plant cover, magazine holder or laundry basket.",
         specs=["Traditional Khasi design", "Cane-bound rim", "Keep dry"],
         hi=("खासी बांस की टोकरी (खोह)", "खासी पहाड़ियों की पारंपरिक पतली होती बांस की टोकरी।"),
         te=("ఖాసీ వెదురు మోసే బుట్ట (ఖో)", "ఖాసీ కొండల సంప్రదాయ వెదురు బుట్ట.")),
    dict(slug="bamboo-bread-basket-set", photo=8093411, maker="tripura", category="Cane & Bamboo",
         name="Handwoven Bamboo Bread Baskets (Set of 2)", craft="Tripura Bamboo Craft",
         material="Bamboo", color="Natural", technique="Twill weave",
         dimensions="25 cm and 20 cm diameter, 6 cm height", weight="450 g", time="2 days",
         price=780, costs=(90, 300, 80), stock=22,
         short="Two shallow bamboo baskets for rotis, bread or fruit.",
         desc="Line these shallow woven baskets with a napkin to keep rotis warm at the table, or use them for fruit and bread. The fine twill weave is lightweight and easy to wipe clean.",
         specs=["Set of 2", "Wipe with a damp cloth", "Air dry fully"],
         hi=("हाथ से बुनी बांस की रोटी टोकरियाँ (2 का सेट)", "रोटी और फलों के लिए बांस की दो उथली टोकरियाँ।"),
         te=("చేతితో అల్లిన వెదురు రొట్టె బుట్టలు (2 సెట్)", "రొట్టెలు, పండ్ల కోసం రెండు లోతు తక్కువ వెదురు బుట్టలు.")),

    # ── Woodcraft & Carving ──────────────────────────────────────────
    dict(slug="channapatna-spinning-tops", photo=39468207, maker="channapatna", category="Woodcraft & Carving",
         crop=(0.0, 0.08, 1.0, 0.82),
         name="Channapatna Lacquered Spinning Tops (Set of 6)", craft="Channapatna Toys",
         material="Hale wood with lac colours", color="Multicolour", technique="Hand turned on a lathe, lac lacquered",
         dimensions="About 6 cm each", weight="300 g", time="2 days",
         price=450, costs=(60, 180, 40), stock=40, badge=GI, featured=True,
         short="Six bright, child-safe spinning tops turned and lacquered by hand in Channapatna.",
         desc="Channapatna, the toy town of Karnataka, turns soft hale wood on a lathe and colours it with lac while it spins, which gives these tops their glossy stripes. The colours are child safe, and the tops spin beautifully on any flat floor.",
         specs=["Set of 6", "Child-safe lac colours", "Suitable for ages 3+"],
         hi=("चन्नपटना लाख वाले लट्टू (6 का सेट)", "चन्नपटना में हाथ से बने चमकदार, बच्चों के लिए सुरक्षित छह लट्टू।"),
         te=("చెన్నపట్న లక్క బొంగరాలు (6 సెట్)", "చెన్నపట్నలో చేతితో చేసిన రంగుల, పిల్లలకు సురక్షిత బొంగరాలు.")),
    dict(slug="carved-wooden-elephant-pair", photo=11450666, maker="mysuru", category="Woodcraft & Carving",
         name="Hand-Carved Wooden Elephant Pair (Mother and Calf)", craft="Mysore Wood Carving",
         material="Sheesham wood", color="Natural rosewood polish", technique="Hand carving with wax polish",
         dimensions="25 cm and 12 cm height", weight="1.6 kg", time="14 days",
         price=4800, costs=(1300, 1900, 200), stock=4, featured=True,
         short="A mother elephant and calf carved from a single block of sheesham wood.",
         desc="Carved by hand over two weeks, this pair shows the fine detailing Mysuru carvers are known for, from the folds of the ears to the raised trunks, a sign of good luck. Finished with a natural wax polish that deepens the grain.",
         specs=["Solid sheesham wood", "Natural wax polish", "Dust with a dry cloth"],
         hi=("हाथ से तराशी लकड़ी की हाथी जोड़ी (माँ और बच्चा)", "शीशम की लकड़ी से हाथ से तराशी हथिनी और उसका बच्चा।"),
         te=("చేతితో చెక్కిన చెక్క ఏనుగుల జంట (తల్లి, పిల్ల)", "శీషం చెక్కతో చేతితో చెక్కిన తల్లి ఏనుగు, పిల్ల ఏనుగు.")),
    dict(slug="carved-sheesham-money-box", photo=6534321, maker="saharanpur", category="Woodcraft & Carving",
         crop=(0.05, 0.15, 0.95, 1.0),
         name="Carved Sheesham Wood Money Box with Lock", craft="Saharanpur Wood Carving",
         material="Sheesham wood with brass lock", color="Honey brown", technique="Hand relief carving",
         dimensions="12 × 12 × 10 cm", weight="600 g", time="5 days",
         price=890, costs=(190, 300, 70), stock=18, badge=GI,
         short="A carved wooden gullak with a coin slot, brass lock and key.",
         desc="Saharanpur carvers cut the floral bands on this money box by hand, then finish it with a warm honey polish. A small brass lock and key keep savings safe, which makes it a thoughtful gift for children.",
         specs=["Coin slot with brass lock and key", "Hand-carved relief", "Solid sheesham wood"],
         hi=("ताले वाली नक्काशीदार शीशम गुल्लक", "पीतल के ताले वाली हाथ से नक्काशीदार लकड़ी की गुल्लक।"),
         te=("తాళంతో చెక్కిన శీషం చెక్క హుండీ", "ఇత్తడి తాళంతో చేతితో చెక్కిన చెక్క డబ్బుల హుండీ.")),
    dict(slug="sheesham-nesting-bowl-set", photo=31703678, maker="saharanpur", category="Woodcraft & Carving",
         name="Sheesham Wood Nesting Bowl Set (5 pieces)", craft="Saharanpur Woodcraft",
         material="Sheesham wood with food-safe oil finish", color="Dark grain brown", technique="Lathe turned and hand sanded",
         dimensions="Large bowl 25 cm, small bowls 12 cm", weight="1.3 kg", time="6 days",
         price=2200, costs=(520, 780, 120), stock=8,
         short="One large and four small sheesham bowls with striking natural grain.",
         desc="Turned from sheesham wood and sealed with a food-safe oil, this set is made for dry snacks, salads and fruit. The four small bowls nest inside the large one, so the whole set stores in the space of a single bowl.",
         specs=["Food-safe oil finish", "Hand wash only, oil occasionally", "Not for microwave"],
         hi=("शीशम लकड़ी के कटोरे (5 का सेट)", "सुंदर प्राकृतिक रेशों वाले शीशम लकड़ी के पाँच कटोरे।"),
         te=("శీషం చెక్క గిన్నెల సెట్ (5)", "సహజ చారలతో అందమైన ఐదు శీషం చెక్క గిన్నెలు.")),
    dict(slug="mango-wood-serving-set", photo=6962761, maker="saharanpur", category="Woodcraft & Carving",
         name="Mango Wood Serving Plates and Bowl Set", craft="Saharanpur Woodcraft",
         material="Mango wood with food-safe finish", color="Two-tone brown", technique="Lathe turned",
         dimensions="Plates 28 cm, bowl 15 cm", weight="1.1 kg", time="4 days",
         price=1650, costs=(360, 560, 110), stock=12,
         short="Two wide mango wood platters and a matching bowl for serving and styling.",
         desc="Mango wood comes from trees that no longer fruit, so it is a sustainable choice. These smooth platters are ideal for cheese, dry fruits or festive sweets, and the matching bowl completes the set.",
         specs=["Set of 3", "Food-safe finish", "Hand wash and dry immediately"],
         hi=("आम की लकड़ी की सर्विंग प्लेट व कटोरी सेट", "आम की लकड़ी की दो बड़ी प्लेटें और एक कटोरी।"),
         te=("మామిడి చెక్క సర్వింగ్ ప్లేట్లు, గిన్నె సెట్", "మామిడి చెక్కతో రెండు పెద్ద ప్లేట్లు, ఒక గిన్నె.")),
    dict(slug="hand-painted-wooden-elephant", photo=36769191, maker="udaipur", category="Woodcraft & Carving",
         crop=(0.0, 0.05, 0.75, 0.95),
         name="Hand-Painted Wooden Elephant Figurine", craft="Rajasthani Painted Woodcraft",
         material="Mango wood with water-based paints", color="Black, white and copper", technique="Hand carved and hand painted",
         dimensions="18 cm height, 22 cm length", weight="700 g", time="6 days",
         price=1250, costs=(180, 480, 90), stock=10,
         short="A carved elephant decorated with fine white brush patterns and a copper finish.",
         desc="Painters in Udaipur decorate each carved elephant freehand with dots, paisleys and borders, echoing the caparisoned elephants of Rajasthani festivals. A lovely accent for a bookshelf or entryway.",
         specs=["Hand painted, so patterns vary", "Mango wood", "Dust with a soft cloth"],
         hi=("हाथ से रंगी लकड़ी की हाथी मूर्ति", "बारीक सफेद डिज़ाइन से हाथ से रंगी लकड़ी की हाथी मूर्ति।"),
         te=("చేతితో రంగులు వేసిన చెక్క ఏనుగు బొమ్మ", "సన్నని తెలుపు డిజైన్లతో చేతితో రంగులు వేసిన ఏనుగు బొమ్మ.")),

    # ── Metal Craft & Bell Metal ─────────────────────────────────────
    dict(slug="bastar-dhokra-spouted-vessel", photo=39032263, maker="bastar", category="Metal Craft & Bell Metal",
         crop=(0.48, 0.06, 0.93, 0.88),
         name="Bastar Dhokra Spouted Vessel", craft="Dhokra Casting",
         material="Brass, lost-wax cast", color="Antique bronze", technique="Lost-wax casting",
         dimensions="14 cm height", weight="800 g", time="10 days",
         price=2400, costs=(620, 900, 120), stock=5, badge=GI, featured=True,
         short="A lost-wax cast Dhokra vessel decorated with raised tribal figures and spiral threads.",
         desc="Dhokra is one of the world's oldest metal-casting methods. Each vessel starts as a clay core wrapped in hand-rolled wax threads, which are then replaced by molten brass, so no mould is ever reused. That is why every Dhokra piece is truly one of a kind.",
         specs=["Lost-wax cast, one of a kind", "Decorative use", "Wipe with a dry cloth; avoid polish"],
         hi=("बस्तर ढोकरा टोंटी वाला पात्र", "मोम-ढलाई से बना आदिवासी आकृतियों वाला ढोकरा पात्र।"),
         te=("బస్తర్ ఢోక్రా ముక్కు పాత్ర", "మైనపు పోత పద్ధతిలో చేసిన గిరిజన బొమ్మల ఢోక్రా పాత్ర.")),
    dict(slug="brass-ganesha-tree-idol", photo=12573352, maker="moradabad", category="Metal Craft & Bell Metal",
         crop=(0.0, 0.05, 1.0, 0.95),
         name="Brass Ganesha Idol with Tree Backdrop", craft="Moradabad Brassware",
         material="Solid brass", color="Antique gold", technique="Sand casting and hand chasing",
         dimensions="26 cm height", weight="2.4 kg", time="9 days",
         price=3400, costs=(1450, 900, 180), stock=6, badge=GI,
         short="A seated Ganesha in solid brass framed by a detailed tree of life.",
         desc="Cast in solid brass and finished by hand in Moradabad, the city of brass, this idol shows Ganesha seated beneath a tree of life. The antique finish highlights the fine chasing on his crown and ornaments. A graceful centrepiece for a home temple or entrance.",
         specs=["Solid brass, not hollow", "Antique hand finish", "Clean with a soft dry cloth"],
         hi=("पेड़ की पृष्ठभूमि वाली पीतल की गणेश मूर्ति", "जीवन-वृक्ष के नीचे विराजमान ठोस पीतल की गणेश मूर्ति।"),
         te=("చెట్టు నేపథ్యంతో ఇత్తడి గణేశ విగ్రహం", "జీవ వృక్షం కింద కూర్చున్న ఘన ఇత్తడి గణేశ విగ్రహం.")),
    dict(slug="swamimalai-bronze-krishna", photo=33799082, maker="swamimalai", category="Metal Craft & Bell Metal",
         crop=(0.12, 0.1, 0.88, 1.0),
         name="Swamimalai Bronze Venugopal Krishna", craft="Swamimalai Bronze Icons",
         material="Bronze alloy of copper, brass and tin", color="Antique copper bronze", technique="Lost-wax casting",
         dimensions="30 cm height", weight="3.1 kg", time="25 days",
         price=12500, costs=(4200, 4500, 300), stock=2, badge=GI, featured=True,
         short="Krishna playing the flute, cast in bronze by the sthapathi families of Swamimalai.",
         desc="Swamimalai's bronze casters follow the proportions laid down in the Shilpa Shastras. This Venugopal Krishna is modelled in wax, cast in bronze and then refined for weeks with chisels and files. A collector's piece that will last generations.",
         specs=["Lost-wax cast bronze", "Hand finished over 25 days", "Ships in a padded wooden crate"],
         hi=("स्वामीमलाई कांस्य वेणुगोपाल कृष्ण", "स्वामीमलाई के कारीगरों द्वारा कांसे में ढली बांसुरी बजाते कृष्ण की मूर्ति।"),
         te=("స్వామిమలై కంచు వేణుగోపాల కృష్ణుడు", "స్వామిమలై శిల్పులు కంచుతో పోసిన వేణుగోపాల కృష్ణ విగ్రహం.")),
    dict(slug="brass-embossed-elephant", photo=10543346, maker="moradabad", category="Metal Craft & Bell Metal",
         crop=(0.0, 0.18, 1.0, 0.9),
         name="Brass Embossed Elephant Figurine", craft="Moradabad Brassware",
         material="Solid brass", color="Bright gold", technique="Casting and hand embossing",
         dimensions="12 cm height, 16 cm length", weight="1.1 kg", time="6 days",
         price=1950, costs=(780, 520, 120), stock=10, badge=GI,
         short="A polished brass elephant covered in hand-embossed floral detail.",
         desc="Elephants with raised trunks are a traditional symbol of good fortune. This brass figurine is cast and then embossed by hand, so the floral patterns shine against the polished body. A classic housewarming gift.",
         specs=["Solid brass", "Hand embossed", "Polish occasionally with brass cleaner"],
         hi=("उभरी नक्काशी वाला पीतल का हाथी", "हाथ से उभरे फूलों वाली चमकदार पीतल की हाथी मूर्ति।"),
         te=("ఉబ్బెత్తు నక్కాషీ ఇత్తడి ఏనుగు", "చేతితో ఉబ్బెత్తు పూల నక్కాషీ మెరిసే ఇత్తడి ఏనుగు.")),
    dict(slug="brass-temple-bell", photo=10686421, maker="moradabad", category="Metal Craft & Bell Metal",
         crop=(0.3, 0.0, 0.72, 1.0),
         name="Hand-Cast Brass Temple Bell", craft="Moradabad Brassware",
         material="Brass", color="Antique gold", technique="Casting with hand engraving",
         dimensions="10 cm bell, 18 cm with hook", weight="650 g", time="5 days",
         price=1250, costs=(480, 330, 90), stock=14,
         short="A hanging brass bell with an engraved body and a clear, lingering ring.",
         desc="This temple-style bell is cast in brass and engraved by hand. Hang it at your entrance, balcony or puja space; its bright tone carries through the house.",
         specs=["Hanging hook included", "Hand engraved", "Suitable indoors or in a covered balcony"],
         hi=("हाथ से ढली पीतल की मंदिर घंटी", "हाथ से उकेरी गई, मधुर ध्वनि वाली पीतल की घंटी।"),
         te=("చేతితో పోసిన ఇత్తడి గుడి గంట", "చేతి చెక్కడంతో, మధుర నాదం చేసే ఇత్తడి గంట.")),
    dict(slug="brass-oil-diya-set", photo=34431714, maker="moradabad", category="Metal Craft & Bell Metal",
         crop=(0.0, 0.2, 1.0, 0.85),
         name="Brass Oil Diya Set (Set of 3)", craft="Moradabad Brassware",
         material="Brass", color="Gold", technique="Sand casting and polishing",
         dimensions="About 8 cm diameter each", weight="600 g", time="4 days",
         price=1100, costs=(420, 280, 80), stock=25,
         short="Three reusable brass diyas for daily lamps and festivals.",
         desc="Unlike clay lamps, these polished brass diyas last for years and only grow more beautiful with use. Fill with ghee or oil and a cotton wick for evening prayers or Diwali.",
         specs=["Set of 3", "Reusable brass", "Wash with tamarind or brass cleaner"],
         hi=("पीतल के तेल दीये (3 का सेट)", "सालों चलने वाले पीतल के तीन दीये।"),
         te=("ఇత్తడి నూనె దీపాలు (3 సెట్)", "ఏళ్ల తరబడి వాడగల మూడు ఇత్తడి ప్రమిదలు.")),

    # ── Traditional Paintings ────────────────────────────────────────
    dict(slug="madhubani-fish-lotus-painting", photo=34961656, maker="mithila", category="Traditional Paintings",
         crop=(0.0, 0.0, 1.0, 1.0),
         name="Madhubani Fish and Lotus Painting on Handmade Paper", craft="Madhubani Painting",
         material="Handmade paper with natural and poster colours", color="Multicolour on ivory", technique="Bharni (filled) style",
         dimensions="38 × 56 cm, unframed", weight="150 g", time="9 days",
         price=2600, costs=(180, 1500, 120), stock=3, badge=GI, featured=True,
         short="A vivid Madhubani painting of a fish among lotuses, painted freehand on handmade paper.",
         desc="In Mithila homes, fish and lotuses are painted for prosperity and new beginnings. This original work uses the bharni style, where outlines are filled with bold, flat colour, framed by a hand-drawn floral border. It ships rolled in a sturdy tube.",
         specs=["Original hand painting, unframed", "Ships rolled in a tube", "Keep away from direct sunlight"],
         hi=("हस्तनिर्मित कागज़ पर मधुबनी मछली और कमल चित्र", "हस्तनिर्मित कागज़ पर हाथ से बनी मछली और कमल की मधुबनी पेंटिंग।"),
         te=("చేతి కాగితంపై మధుబని చేప, కమలం చిత్రం", "చేతి కాగితంపై వేసిన చేప, కమలాల మధుబని చిత్రం.")),
    dict(slug="madhubani-goddess-painting", photo=30108529, maker="mithila", category="Traditional Paintings",
         crop=(0.1, 0.12, 0.84, 0.6),
         name="Madhubani Goddess Painting on Canvas", craft="Madhubani Painting",
         material="Cotton canvas with acrylic colours", color="Red, yellow and indigo", technique="Kachni and bharni styles",
         dimensions="61 × 76 cm, unframed", weight="350 g", time="16 days",
         price=5400, costs=(450, 3200, 200), stock=2, badge=GI,
         short="A large Madhubani canvas of a goddess surrounded by fish, birds and blossoms.",
         desc="This canvas combines the fine-line kachni style with bright bharni fills. The goddess at its centre is framed by fish, birds and flowering creepers, each drawn by hand without any stencil. A statement piece for a living room wall.",
         specs=["Original hand painting on canvas", "Ships rolled; frame locally", "Signed by the artist on the back"],
         hi=("कैनवास पर मधुबनी देवी चित्र", "मछलियों, पक्षियों और फूलों से घिरी देवी की बड़ी मधुबनी पेंटिंग।"),
         te=("కాన్వాస్‌పై మధుబని దేవి చిత్రం", "చేపలు, పక్షులు, పూలతో చుట్టుముట్టిన దేవి పెద్ద మధుబని చిత్రం.")),
    dict(slug="odisha-pattachitra-scroll", photo=22820070, maker="raghurajpur", category="Traditional Paintings",
         crop=(0.55, 0.0, 1.0, 0.58),
         name="Pattachitra Mythological Painting on Cloth", craft="Odisha Pattachitra",
         material="Cloth coated with chalk and tamarind gum, natural colours", color="Red, blue and ochre", technique="Hand painted with fine brushes",
         dimensions="61 × 91 cm", weight="300 g", time="30 days",
         price=8500, costs=(600, 5500, 250), stock=1, badge=GI, featured=True,
         short="A richly detailed Pattachitra scene painted on treated cloth in Raghurajpur.",
         desc="Raghurajpur's chitrakars prepare the 'patta' by coating cloth with chalk and tamarind gum, then paint with colours made from stone, shell and lamp soot. This scene took a month of patient brushwork, with ornate borders framing the central figures.",
         specs=["Original painting, one of a kind", "Natural colours", "Ships rolled with a certificate from the maker"],
         hi=("कपड़े पर पट्टचित्र पौराणिक दृश्य", "रघुराजपुर में प्राकृतिक रंगों से कपड़े पर बना बारीक पट्टचित्र।"),
         te=("వస్త్రంపై పట్టచిత్ర పౌరాణిక దృశ్యం", "రఘురాజ్‌పూర్‌లో సహజ రంగులతో వస్త్రంపై వేసిన పట్టచిత్రం.")),
    dict(slug="bengal-patachitra-coasters", photo=36817155, maker="pingla", category="Traditional Paintings",
         crop=(0.0, 0.05, 1.0, 0.8),
         name="Bengal Patachitra Hand-Painted Wooden Coasters (Set of 4)", craft="Bengal Patachitra",
         material="Wood with natural colours and varnish", color="Multicolour", technique="Hand painted, varnished",
         dimensions="10 × 10 cm each", weight="300 g", time="4 days",
         price=950, costs=(120, 420, 60), stock=15, badge=GI,
         short="Four wooden coasters painted with fish and floral motifs by the patua artists of Pingla.",
         desc="The patuas of Pingla are storytellers who paint and sing their scrolls. Here their bright fish and flower motifs are painted on wooden coasters and sealed with varnish, bringing a little folk art to everyday tea time.",
         specs=["Set of 4", "Varnished, wipe clean", "Not for hot pans"],
         hi=("बंगाल पटचित्र हाथ से पेंट किए लकड़ी के कोस्टर (4)", "पिंगला के पटुआ कलाकारों द्वारा हाथ से रंगे चार लकड़ी के कोस्टर।"),
         te=("బెంగాల్ పటచిత్ర చేతి చిత్రణ చెక్క కోస్టర్లు (4)", "పింగ్లా పటువా కళాకారులు చేతితో రంగులు వేసిన నాలుగు కోస్టర్లు.")),
    dict(slug="pomegranate-mini-canvas", photo=26274827, maker="udaipur", category="Traditional Paintings",
         crop=(0.1, 0.22, 0.9, 0.9),
         name="Hand-Painted Pomegranate Mini Canvas with Easel", craft="Contemporary Miniature Art",
         material="Cotton canvas board with acrylics, pine easel", color="Sky blue with red", technique="Hand painted",
         dimensions="15 × 15 cm canvas, 12 cm easel", weight="150 g", time="2 days",
         price=750, costs=(90, 320, 50), stock=20,
         short="A small hand-painted pomegranate branch on canvas, with its own wooden easel.",
         desc="Pomegranates are a favourite motif in Rajasthani miniatures, symbolising abundance. This little canvas comes ready to display on its easel, making it an easy gift for a desk or bedside table.",
         specs=["Easel included", "Original hand painting", "Ready to display"],
         hi=("ईज़ल सहित हाथ से पेंट किया अनार मिनी कैनवास", "लकड़ी के ईज़ल के साथ हाथ से बना अनार की डाली का छोटा कैनवास।"),
         te=("ఈజిల్‌తో చేతి చిత్రణ దానిమ్మ మినీ కాన్వాస్", "చెక్క ఈజిల్‌తో చేతితో వేసిన దానిమ్మ కొమ్మ చిన్న కాన్వాస్.")),
    dict(slug="rajasthani-painted-wooden-panel", photo=37148173, maker="udaipur", category="Traditional Paintings",
         crop=(0.25, 0.3, 0.78, 1.0),
         name="Rajasthani Folk-Painted Wooden Wall Panel", craft="Rajasthani Folk Painting",
         material="Reclaimed wood with natural pigments", color="Ivory, saffron and teal", technique="Hand painted",
         dimensions="120 × 30 cm", weight="4.5 kg", time="12 days",
         price=7200, costs=(1800, 2800, 450), stock=1,
         short="A tall reclaimed-wood panel hand-painted with a traditional Rajasthani figure.",
         desc="Painted on reclaimed wood, this panel carries a figure in the folk style seen on old Rajasthani havelis. The weathered surface is left visible around the painting, so it looks at home in both rustic and modern interiors.",
         specs=["One of a kind", "Reclaimed wood, marks are part of its character", "Wall mounting hooks included"],
         hi=("राजस्थानी लोक-चित्रित लकड़ी का दीवार पैनल", "पुरानी लकड़ी पर हाथ से बनी राजस्थानी लोक आकृति वाला पैनल।"),
         te=("రాజస్థానీ జానపద చిత్రణ చెక్క గోడ ప్యానెల్", "పాత చెక్కపై చేతితో వేసిన రాజస్థానీ జానపద బొమ్మ ప్యానెల్.")),
]

# Wide editorial photographs for the storefront (illustrative, not tied to any listing).
BANNERS = {
    "hero-weaver.jpg": 32673642,
    "hero-potter.jpg": 36779010,
    "hero-blockprint.jpg": 7037689,
    "hero-woodcarver.jpg": 37011185,
}
