import React, { createContext, useContext, useEffect, useState } from 'react';

export const LANGUAGE_OPTIONS = [
  { code: 'en', name: 'English', label: 'English', speechCode: 'en-IN' },
  { code: 'hi', name: 'Hindi', label: 'हिन्दी', speechCode: 'hi-IN' },
  { code: 'te', name: 'Telugu', label: 'తెలుగు', speechCode: 'te-IN' },
];

export const normalizeLocale = (value) => {
  const text = String(value || '').toLowerCase();
  if (text.startsWith('te') || text.includes('తెలుగు')) return 'te';
  if (text.startsWith('hi') || text.includes('हिन्द') || text.includes('हिंदी')) return 'hi';
  return 'en';
};

const translations = {
  hi: {
    'Independent makers. Thoughtful choices.': 'स्वतंत्र कारीगर। सोच-समझकर चुनी चीज़ें।',
    'Shop by category': 'श्रेणी के अनुसार खरीदें', 'Objects with a soul': 'हर चीज़ में एक कहानी',
    'Handcrafted for a': 'हाथों से बना,', 'life well lived.': 'आपकी ज़िंदगी के लिए।',
    'Discover textiles, thoughtful homeware, and traditional art — with the maker’s story in every detail.': 'कपड़े, घर की खास चीज़ें और पारंपरिक कला खोजें — हर बारीकी में कारीगर की कहानी।',
    'Shop the collection': 'संग्रह से खरीदें', 'Craft. Character. Connection.': 'शिल्प। पहचान। जुड़ाव।',
    'The CraftLink experience': 'CraftLink का अनुभव', 'Discover the people behind the products': 'उत्पाद बनाने वाले लोगों को जानें',
    'Your language, your comfort': 'आपकी भाषा, आपका आराम', 'English, Hindi & Telugu': 'अंग्रेज़ी, हिन्दी और तेलुगु',
    'Details before you decide': 'चुनने से पहले पूरी जानकारी', 'Explore materials, origins, and prices': 'सामग्री, स्थान और कीमत देखें',
    'Discover your craft': 'अपना पसंदीदा शिल्प खोजें', 'A world of handmade.': 'हाथों से बनी चीज़ों की दुनिया।',
    'View all products': 'सभी उत्पाद देखें', 'Browse': 'देखें', 'Woven with character': 'खास बुनाई, खास पहचान',
    'Form meets function': 'सुंदर और काम की', 'Naturally beautiful': 'कुदरती खूबसूरती', 'Made to be kept': 'सहेजकर रखने लायक',
    'Details that shine': 'चमकती बारीकियाँ', 'Art with a story': 'कला के पीछे एक कहानी',
    'Made with care. Chosen by you.': 'प्यार से बना। आपके लिए।', 'Name: A to Z': 'नाम: A से Z',
    'Recently listed': 'हाल में जोड़े गए', 'Any price': 'कोई भी कीमत', 'In stock only': 'केवल उपलब्ध उत्पाद',
    'Showing filtered products': 'चुने हुए फ़िल्टर के उत्पाद', 'of': 'में से', 'products': 'उत्पाद',
    'Show more products': 'और उत्पाद देखें', 'The collection is growing': 'नए शिल्प जल्द आएँगे',
    'Published artisan products will appear here. Check back soon.': 'कारीगरों के प्रकाशित उत्पाद यहाँ दिखेंगे। जल्द फिर देखें।',
    'Pottery taking shape in an artisan workshop': 'कारीगर की कार्यशाला में बनते मिट्टी के बर्तन',
    'The art of making': 'बनाने की कला', 'For the hands that create': 'सृजन करने वाले हाथों के लिए',
    'Your craft deserves': 'आपका शिल्प पहुँचे', 'a bigger audience.': 'और ज़्यादा लोगों तक।',
    'Bring your products online with guided photo enhancement and simple voice questions in your language.': 'बेहतर फोटो और अपनी भाषा में आसान आवाज़ वाले सवालों की मदद से अपने उत्पाद ऑनलाइन लाएँ।',
    'Add a photo': 'फोटो जोड़ें', 'Tell your story': 'अपनी कहानी बताएँ', 'Create your listing': 'उत्पाद की जानकारी बनाएँ',
    'Start selling': 'बेचना शुरू करें', 'Photo unavailable': 'फोटो उपलब्ध नहीं',
    'Sign in to track your orders and manage your account.': 'अपने ऑर्डर देखने और खाता संभालने के लिए साइन इन करें।',
    'Manage your products, orders, and inventory in one place.': 'अपने उत्पाद, ऑर्डर और स्टॉक एक जगह संभालें।',
    'New to CraftLink?': 'CraftLink पर नए हैं?', 'Already have an account?': 'पहले से खाता है?', 'Phone Number': 'फ़ोन नंबर',
    'Clear search': 'खोज हटाएँ',
    'AI Computer Vision: Removing background & enhancing studio quality...': 'आपकी फोटो का बैकग्राउंड साफ़ कर रहे हैं और उसे बेहतर बना रहे हैं…',
    'Preparing your first simple question…': 'आपके लिए पहला आसान सवाल तैयार कर रहे हैं…',
    'Checking the words we heard…': 'आपकी कही बात जाँच रहे हैं…',
    'Saving your answer and preparing the next step…': 'आपका जवाब सहेज रहे हैं और अगला कदम तैयार कर रहे हैं…',
    'Generating a verified bilingual marketplace listing...': 'आपके जवाबों से उत्पाद की जानकारी तैयार कर रहे हैं…',
    'Pricing AI: Blending confirmed costs with regional market benchmarks...': 'आपके खर्च और बाज़ार की जानकारी से कीमत का अनुमान लगा रहे हैं…',
    'Submitting to Admin Approval Queue...': 'आपका उत्पाद समीक्षा के लिए भेज रहे हैं…',
    'Close': 'बंद करें', 'Your full name': 'आपका पूरा नाम', 'Email or phone': 'ईमेल या फ़ोन', 'Password': 'पासवर्ड',
    'Create your account': 'अपना खाता बनाएँ', 'Sign in to CraftLink': 'CraftLink में साइन इन करें', 'Seller sign in': 'विक्रेता साइन इन', 'Please wait…': 'कृपया रुकें…',
    'Category': 'श्रेणी', 'Material': 'सामग्री', 'Origin': 'स्थान', 'Dimensions': 'आकार', 'Production time': 'बनाने का समय',
    'Quantity': 'संख्या', 'Increase quantity': 'संख्या बढ़ाएँ', 'Decrease quantity': 'संख्या घटाएँ', 'Added to cart': 'कार्ट में जोड़ा गया',
    'Your cart': 'आपका कार्ट', 'Your cart is empty': 'आपका कार्ट खाली है', 'Continue shopping': 'खरीदारी जारी रखें',
    'Remove': 'हटाएँ', 'Subtotal': 'कुल कीमत', 'Proceed to checkout': 'चेकआउट करें', 'items': 'वस्तुएँ',
    'Shipping is calculated at checkout.': 'डिलीवरी शुल्क चेकआउट पर दिखेगा।',
    'Language': 'भाषा', 'Shop crafts': 'शिल्प खरीदें', 'Sell with us': 'हमारे साथ बेचें',
    'Orders': 'ऑर्डर', 'Cart': 'कार्ट', 'Account': 'खाता', 'Sign in': 'साइन इन',
    'Sign out': 'साइन आउट', 'Seller workspace': 'विक्रेता कार्यक्षेत्र', 'Marketplace': 'बाज़ार',
    'Administration': 'प्रशासन', 'Search crafts, materials, or artisans…': 'शिल्प, सामग्री या कारीगर खोजें…',
    'Search': 'खोजें', 'All crafts': 'सभी शिल्प', 'Handloom': 'हथकरघा', 'Pottery': 'मिट्टी के शिल्प',
    'Woodcraft': 'लकड़ी के शिल्प', 'Metal art': 'धातु कला', 'Bamboo': 'बाँस', 'Paintings': 'चित्रकला',
    'Made by hand. Chosen with heart.': 'हाथों से बना। दिल से चुना।',
    'Discover the craft. Meet the maker.': 'शिल्प खोजें। कारीगर से जुड़ें।',
    'Thoughtful pieces, made by independent artisans. Explore textiles, pottery, and everyday objects with a story.': 'स्वतंत्र कारीगरों की बनाई खास चीज़ें। कपड़े, मिट्टी के शिल्प और रोज़मर्रा की चीज़ों के पीछे की कहानी खोजें।',
    'Explore the collection': 'संग्रह देखें', 'Start your artisan store': 'अपना शिल्प स्टोर शुरू करें',
    'The craft collection': 'शिल्प संग्रह', 'Find something that feels like you.': 'अपने मन की चीज़ खोजें।',
    'pieces to discover': 'चीज़ें उपलब्ध', 'Filters': 'फ़िल्टर', 'Clear filters': 'फ़िल्टर हटाएँ',
    'Sort by': 'क्रम चुनें', 'Recommended': 'सुझाए गए', 'Price: low to high': 'कीमत: कम से अधिक',
    'Price: high to low': 'कीमत: अधिक से कम', 'Maximum price': 'अधिकतम कीमत',
    'No crafts found': 'कोई शिल्प नहीं मिला', 'Try another search or clear your filters.': 'दूसरा शब्द खोजें या फ़िल्टर हटाएँ।',
    'Loading the collection…': 'संग्रह लोड हो रहा है…', 'Could not load the collection.': 'संग्रह लोड नहीं हो पाया।',
    'Try again': 'फिर कोशिश करें', 'View product': 'उत्पाद देखें', 'Add to cart': 'कार्ट में जोड़ें',
    'Buy now': 'अभी खरीदें', 'Out of stock': 'स्टॉक समाप्त', 'Artisan craft': 'कारीगर का शिल्प',
    'GI certified': 'GI प्रमाणित', 'Direct from the maker': 'सीधे कारीगर से', 'Your journey, your language': 'आपकी यात्रा, आपकी भाषा',
    'Shop and create listings in English, Hindi, or Telugu.': 'अंग्रेज़ी, हिन्दी या तेलुगु में खरीदारी करें और उत्पाद जोड़ें।',
    'CraftLink connects people with the hands behind the craft.': 'CraftLink आपको शिल्प बनाने वाले हाथों से जोड़ता है।',
    'Back to top': 'ऊपर जाएँ', 'Explore': 'खोजें', 'For artisans': 'कारीगरों के लिए', 'Your purchases': 'आपकी खरीदारी',
    'Create a store': 'स्टोर बनाएँ', 'Track an order': 'ऑर्डर ट्रैक करें', 'All rights reserved.': 'सर्वाधिकार सुरक्षित।',
    'Dashboard': 'डैशबोर्ड', 'AI Listing Studio': 'AI उत्पाद स्टूडियो', 'My Inventory': 'मेरे उत्पाद',
    'Orders & Shipments': 'ऑर्डर और शिपमेंट', 'Payments & Payouts': 'भुगतान', 'Analytics': 'विश्लेषण',
    'Main Menu': 'मुख्य मेन्यू', 'View Your Storefront': 'अपना बाज़ार देखें', 'Add Listing': 'उत्पाद जोड़ें',
    'Your Store': 'आपका स्टोर', 'Active Store Profile': 'सक्रिय स्टोर', '+ Register New Store': '+ नया स्टोर बनाएँ',
    'Seller Dashboard': 'विक्रेता डैशबोर्ड', 'My Inventory & Catalog': 'मेरे उत्पाद और कैटलॉग',
    'Analytics & Insights': 'विश्लेषण और जानकारी', 'Storefront': 'बाज़ार', 'Open navigation': 'मेन्यू खोलें',
    'Close navigation': 'मेन्यू बंद करें', 'Your creative workspace': 'आपका रचनात्मक कार्यक्षेत्र',
    'A photo. Your story. A listing ready to share.': 'एक फोटो। आपकी कहानी। बेचने के लिए तैयार उत्पाद।',
    'We guide you one step at a time. You can speak or type in your language.': 'हम हर कदम पर मदद करेंगे। आप अपनी भाषा में बोल या लिख सकते हैं।',
    'Add Photo': 'फोटो जोड़ें', 'Answer Questions': 'सवालों के जवाब दें', 'Check Details': 'जानकारी जाँचें',
    'See Fair Price': 'उचित कीमत देखें', 'Send for Review': 'समीक्षा के लिए भेजें',
    'AI cleans the image': 'AI फोटो साफ़ करेगा', 'One simple question at a time': 'एक समय में एक आसान सवाल',
    'Review your words': 'अपने जवाब जाँचें', 'Clear cost calculation': 'खर्च का स्पष्ट हिसाब', 'Final submission': 'अंतिम चरण',
    'First, add one product photo': 'पहले उत्पाद की एक फोटो जोड़ें', 'Do not worry about the background. AI will clean it.': 'बैकग्राउंड की चिंता न करें। AI इसे साफ़ करेगा।',
    'Tap here and choose a photo': 'यहाँ दबाकर फोटो चुनें', 'JPG, PNG or WebP — up to 15MB': 'JPG, PNG या WebP — अधिकतम 15MB',
    'Your photo is ready': 'आपकी फोटो तैयार है', 'Next: Answer simple questions': 'आगे: आसान सवालों के जवाब दें',
    'Photo preview': 'फोटो का पूर्वावलोकन', 'Your enhanced photo will appear here': 'आपकी बेहतर फोटो यहाँ दिखेगी',
    'Choose a clear photo with the whole product visible.': 'एक साफ़ फोटो चुनें जिसमें पूरा उत्पाद दिखे।',
    'Nothing is submitted until you review and confirm.': 'आपकी जाँच और पुष्टि के बाद ही उत्पाद भेजा जाएगा।',
    'Please wait. We are preparing the next step for you.': 'कृपया रुकें। हम आपके लिए अगला कदम तैयार कर रहे हैं।',
    'Updating the question language…': 'सवाल की भाषा बदल रहे हैं…', 'Check your product details': 'अपने उत्पाद की जानकारी जाँचें',
    'Nothing is submitted yet. Read the details below and use Edit if anything needs changing.': 'अभी कुछ भेजा नहीं गया है। नीचे की जानकारी पढ़ें और बदलने के लिए संपादित करें दबाएँ।',
    'Edit': 'संपादित करें', 'Save': 'सहेजें', 'Based only on your answers': 'आपके जवाबों पर आधारित',
    'Product details': 'उत्पाद की जानकारी', 'Details from your photo and answers': 'आपकी फोटो और जवाबों से मिली जानकारी',
    'Your product story': 'आपके उत्पाद की कहानी', 'Listen': 'सुनें', 'Stop': 'रोकें',
    // Seller workspace
    'My shop': 'मेरी दुकान',
    'My products': 'मेरे उत्पाद',
    'Add a product': 'नया उत्पाद जोड़ें',
    'My money': 'मेरी कमाई',
    'How I am doing': 'मेरा काम कैसा चल रहा है',
    'My shop details': 'दुकान की जानकारी',
    'Store': 'दुकान',
    'Business': 'कारोबार',
    'Seller Central': 'विक्रेता केंद्र',
    'My shop today': 'आज मेरी दुकान',
    'A quick look at what is happening': 'एक नज़र में आज का हाल',
    'Add a new product': 'नया उत्पाद जोड़ें',
    'One photo, a few easy questions, and you are done': 'एक फोटो, कुछ आसान सवाल, और काम पूरा',
    'Everything you have put up for sale': 'आपने बिक्री के लिए जो रखा है',
    'Confirm, pack and send what buyers ordered': 'ऑर्डर पक्का करें, पैक करें और भेजें',
    'What you have earned and what is on the way': 'आपने कितना कमाया और कितना आना बाकी है',
    'What sells well, and what needs care': 'क्या अच्छा बिक रहा है और किस पर ध्यान चाहिए',
    'What buyers and our team can see': 'खरीदार और हमारी टीम क्या देख सकते हैं',
    'View storefront': 'दुकान देखें',
    'Refresh': 'ताज़ा करें',
    'Live': 'लाइव',
    'updated': 'अपडेट हुआ',
    'just now': 'अभी-अभी',
    'minute ago': 'मिनट पहले',
    'minutes ago': 'मिनट पहले',
    'hour ago': 'घंटा पहले',
    'hours ago': 'घंटे पहले',
    'day ago': 'दिन पहले',
    'days ago': 'दिन पहले',
    'Good morning': 'सुप्रभात',
    'Good afternoon': 'नमस्कार',
    'Good evening': 'शुभ संध्या',
    'You have': 'आपके पास',
    'order to send today.': 'ऑर्डर आज भेजना है।',
    'orders to send today.': 'ऑर्डर आज भेजने हैं।',
    'Everything is calm right now. Your shop is open and taking orders.': 'अभी सब शांत है। आपकी दुकान खुली है और ऑर्डर ले रही है।',
    'Let us put your first product online today.': 'आइए आज आपका पहला उत्पाद ऑनलाइन करें।',
    'Listen to my summary': 'मेरा हाल सुनें',
    'Money from sales': 'बिक्री से कमाई',
    'Orders to send': 'भेजने वाले ऑर्डर',
    'Products on sale': 'बिक्री पर उत्पाद',
    'Cash received': 'मिला हुआ पैसा',
    'order': 'ऑर्डर',
    'orders': 'ऑर्डर',
    'piece': 'नग',
    'pieces': 'नग',
    'New, confirmed or packed': 'नए, पक्के या पैक किए हुए',
    'being checked': 'जाँच में',
    'to fix': 'सुधारने हैं',
    'still on the way': 'अभी आना बाकी',
    'What is happening': 'क्या हो रहा है',
    'Nothing yet today': 'आज अभी कुछ नहीं',
    'Orders and updates will appear here as they happen.': 'ऑर्डर और अपडेट यहाँ तुरंत दिखेंगे।',
    'ordered': 'ने ऑर्डर किया',
    'is live for buyers': 'अब खरीदारों के लिए ऑनलाइन है',
    'came back for changes': 'बदलाव के लिए वापस आया है',
    'is being checked by our team': 'हमारी टीम जाँच रही है',
    'Needs your attention': 'आपके ध्यान की ज़रूरत',
    'order is waiting for you': 'ऑर्डर आपका इंतज़ार कर रहा है',
    'orders are waiting for you': 'ऑर्डर आपका इंतज़ार कर रहे हैं',
    'Confirm, pack and send so buyers are not left waiting': 'ऑर्डर पक्का करें, पैक करें और भेजें ताकि खरीदार इंतज़ार न करें',
    'product came back for changes': 'उत्पाद बदलाव के लिए वापस आया है',
    'Read the note from our team, fix it and send again': 'हमारी टीम का संदेश पढ़िए, सुधारिए और दोबारा भेजिए',
    'product is almost sold out': 'उत्पाद लगभग बिक चुका है',
    'Add more stock so buyers can keep ordering': 'स्टॉक बढ़ाइए ताकि ऑर्डर आते रहें',
    'product is with our team for checking': 'उत्पाद हमारी टीम के पास जाँच के लिए है',
    'We usually finish checking within a working day': 'हम आमतौर पर एक कार्यदिवस में जाँच पूरी कर देते हैं',
    'Latest orders': 'ताज़ा ऑर्डर',
    'See all': 'सभी देखें',
    'Buyer': 'खरीदार',
    'Items': 'सामान',
    'Your share': 'आपका हिस्सा',
    'Status': 'स्थिति',
    'No orders yet': 'अभी कोई ऑर्डर नहीं',
    'When someone buys one of your products, it will appear here straight away.': 'जैसे ही कोई आपका उत्पाद खरीदेगा, वह यहाँ तुरंत दिखेगा।',
    'Tips that help you sell': 'बिक्री बढ़ाने के सुझाव',
    'Take the photo in daylight': 'दिन की रोशनी में फोटो लें',
    'Near a window, on a plain cloth. Clear photos sell far more.': 'खिड़की के पास, सादे कपड़े पर। साफ़ फोटो ज़्यादा बिकती है।',
    'Tell the story of the piece': 'अपने उत्पाद की कहानी बताइए',
    'Buyers love knowing how long it took and who made it.': 'खरीदार जानना चाहते हैं कि इसे किसने और कितने समय में बनाया।',
    'Send orders quickly': 'ऑर्डर जल्दी भेजें',
    'Confirm the same day. Buyers remember sellers who are quick.': 'उसी दिन पक्का करें। तेज़ विक्रेता खरीदारों को याद रहते हैं।',
    'Keep stock up to date': 'स्टॉक सही रखें',
    'If a piece is sold out, update it so nobody is disappointed.': 'अगर माल खत्म हो गया है तो अपडेट करें, ताकि किसी को निराशा न हो।',
    'Your very first order has arrived!': 'आपका पहला ऑर्डर आ गया है!',
    'Confirm it today so the buyer knows their piece is on its way.': 'आज ही पक्का करें ताकि खरीदार को पता चले कि सामान आ रहा है।',
    'Your shop is live for buyers': 'आपकी दुकान खरीदारों के लिए खुल गई है',
    'Share your shop link with friends and customers. Orders will show up here the moment they arrive.': 'अपनी दुकान का लिंक दोस्तों और ग्राहकों को भेजिए। ऑर्डर आते ही यहाँ दिखेंगे।',
    'Open orders': 'ऑर्डर खोलें',
    'New order': 'नया ऑर्डर',
    'Welcome to CraftLink': 'CraftLink में आपका स्वागत है',
    'Your shop is ready. Let us add your first product.': 'आपकी दुकान तैयार है। आइए पहला उत्पाद जोड़ें।',
    'Take one photo and answer a few easy questions by speaking or typing. We write the description and suggest a fair price. Nothing goes online until you say yes.': 'एक फोटो लीजिए और बोलकर या लिखकर कुछ आसान सवालों के जवाब दीजिए। हम जानकारी लिखेंगे और सही कीमत बताएँगे। आपकी हाँ के बिना कुछ ऑनलाइन नहीं होगा।',
    'Add my first product': 'मेरा पहला उत्पाद जोड़ें',
    'Take one photo': 'एक फोटो लीजिए',
    'Answer easy questions': 'आसान सवालों के जवाब दीजिए',
    'See a fair price': 'सही कीमत देखिए',
    'Send for checking': 'जाँच के लिए भेजिए',
    'Sales': 'बिक्री',
    'in the last': 'पिछले',
    'days': 'दिनों में',
    'Today': 'आज',
    'Date range': 'समय अवधि',
    'No sales in this period yet. Share your shop link to get started.': 'इस अवधि में अभी कोई बिक्री नहीं। शुरुआत के लिए अपनी दुकान का लिंक साझा कीजिए।',
    'friend': 'दोस्त',
  },
  te: {
    'Independent makers. Thoughtful choices.': 'స్వతంత్ర కళాకారులు. ఆలోచించి ఎంచుకున్న వస్తువులు.',
    'Shop by category': 'వర్గం ప్రకారం కొనండి', 'Objects with a soul': 'ప్రతి వస్తువులో ఒక కథ',
    'Handcrafted for a': 'చేతులతో చేసిన కళ,', 'life well lived.': 'మీ జీవితానికి అందం.',
    'Discover textiles, thoughtful homeware, and traditional art — with the maker’s story in every detail.': 'చేనేత, ఇంటికి ప్రత్యేక వస్తువులు మరియు సంప్రదాయ కళను కనుగొనండి — ప్రతి వివరంలో కళాకారుడి కథ ఉంది.',
    'Shop the collection': 'సేకరణ నుండి కొనండి', 'Craft. Character. Connection.': 'కళ. ప్రత్యేకత. అనుబంధం.',
    'The CraftLink experience': 'CraftLink అనుభవం', 'Discover the people behind the products': 'ఉత్పత్తులు చేసిన కళాకారులను తెలుసుకోండి',
    'Your language, your comfort': 'మీ భాష, మీ సౌకర్యం', 'English, Hindi & Telugu': 'ఇంగ్లీష్, హిందీ మరియు తెలుగు',
    'Details before you decide': 'ఎంచుకునే ముందు పూర్తి వివరాలు', 'Explore materials, origins, and prices': 'పదార్థాలు, ప్రాంతం మరియు ధర చూడండి',
    'Discover your craft': 'మీకు నచ్చిన కళను కనుగొనండి', 'A world of handmade.': 'చేతులతో చేసిన కళా ప్రపంచం.',
    'View all products': 'అన్ని ఉత్పత్తులు చూడండి', 'Browse': 'చూడండి', 'Woven with character': 'ప్రత్యేకతతో నేసినవి',
    'Form meets function': 'అందం మరియు ఉపయోగం', 'Naturally beautiful': 'సహజమైన అందం', 'Made to be kept': 'పదిలంగా ఉంచుకునే కళ',
    'Details that shine': 'మెరిసే నైపుణ్యం', 'Art with a story': 'ఒక కథ చెప్పే కళ',
    'Made with care. Chosen by you.': 'శ్రద్ధతో చేసినవి. మీ కోసం.', 'Name: A to Z': 'పేరు: A నుండి Z',
    'Recently listed': 'ఇటీవల చేర్చినవి', 'Any price': 'ఏ ధరైనా', 'In stock only': 'అందుబాటులో ఉన్నవే',
    'Showing filtered products': 'ఎంచుకున్న ఫిల్టర్ల ఉత్పత్తులు', 'of': 'లో', 'products': 'ఉత్పత్తులు',
    'Show more products': 'మరిన్ని ఉత్పత్తులు చూడండి', 'The collection is growing': 'కొత్త కళాఖండాలు త్వరలో వస్తాయి',
    'Published artisan products will appear here. Check back soon.': 'కళాకారులు ప్రచురించిన ఉత్పత్తులు ఇక్కడ కనిపిస్తాయి. త్వరలో మళ్లీ చూడండి.',
    'Pottery taking shape in an artisan workshop': 'కళాకారుడి పని ప్రదేశంలో తయారవుతున్న మట్టి కుండలు',
    'The art of making': 'తయారుచేసే కళ', 'For the hands that create': 'సృజించే చేతుల కోసం',
    'Your craft deserves': 'మీ కళ చేరాలి', 'a bigger audience.': 'మరింత మందికి.',
    'Bring your products online with guided photo enhancement and simple voice questions in your language.': 'మెరుగైన ఫోటో మరియు మీ భాషలో సులభమైన వాయిస్ ప్రశ్నల సహాయంతో మీ ఉత్పత్తులను ఆన్‌లైన్‌లో చేర్చండి.',
    'Add a photo': 'ఫోటో చేర్చండి', 'Tell your story': 'మీ కథ చెప్పండి', 'Create your listing': 'ఉత్పత్తి వివరాలు చేర్చండి',
    'Start selling': 'అమ్మడం ప్రారంభించండి', 'Photo unavailable': 'ఫోటో అందుబాటులో లేదు',
    'Sign in to track your orders and manage your account.': 'మీ ఆర్డర్లు చూడటానికి మరియు ఖాతాను నిర్వహించడానికి సైన్ ఇన్ చేయండి.',
    'Manage your products, orders, and inventory in one place.': 'మీ ఉత్పత్తులు, ఆర్డర్లు మరియు స్టాక్‌ను ఒకే చోట నిర్వహించండి.',
    'New to CraftLink?': 'CraftLink కు కొత్తా?', 'Already have an account?': 'ఇప్పటికే ఖాతా ఉందా?', 'Phone Number': 'ఫోన్ నంబర్',
    'Clear search': 'వెతికిన పదం తొలగించండి',
    'AI Computer Vision: Removing background & enhancing studio quality...': 'మీ ఫోటో బ్యాక్‌గ్రౌండ్‌ను శుభ్రం చేసి మెరుగుపరుస్తున్నాం…',
    'Preparing your first simple question…': 'మీ కోసం మొదటి సులభమైన ప్రశ్న సిద్ధం చేస్తున్నాం…',
    'Checking the words we heard…': 'మీరు చెప్పిన మాటలను పరిశీలిస్తున్నాం…',
    'Saving your answer and preparing the next step…': 'మీ జవాబు సేవ్ చేసి తదుపరి దశ సిద్ధం చేస్తున్నాం…',
    'Generating a verified bilingual marketplace listing...': 'మీ జవాబులతో ఉత్పత్తి వివరాలు సిద్ధం చేస్తున్నాం…',
    'Pricing AI: Blending confirmed costs with regional market benchmarks...': 'మీ ఖర్చు మరియు మార్కెట్ వివరాలతో ధర అంచనా వేస్తున్నాం…',
    'Submitting to Admin Approval Queue...': 'మీ ఉత్పత్తిని సమీక్ష కోసం పంపుతున్నాం…',
    'Close': 'మూసివేయండి', 'Your full name': 'మీ పూర్తి పేరు', 'Email or phone': 'ఈమెయిల్ లేదా ఫోన్', 'Password': 'పాస్‌వర్డ్',
    'Create your account': 'మీ ఖాతా సృష్టించండి', 'Sign in to CraftLink': 'CraftLink లో సైన్ ఇన్ చేయండి', 'Seller sign in': 'విక్రేత సైన్ ఇన్', 'Please wait…': 'దయచేసి వేచి ఉండండి…',
    'Category': 'వర్గం', 'Material': 'పదార్థం', 'Origin': 'ప్రాంతం', 'Dimensions': 'కొలతలు', 'Production time': 'తయారీ సమయం',
    'Quantity': 'సంఖ్య', 'Increase quantity': 'సంఖ్య పెంచండి', 'Decrease quantity': 'సంఖ్య తగ్గించండి', 'Added to cart': 'కార్ట్‌లో చేర్చబడింది',
    'Your cart': 'మీ కార్ట్', 'Your cart is empty': 'మీ కార్ట్ ఖాళీగా ఉంది', 'Continue shopping': 'కొనుగోలు కొనసాగించండి',
    'Remove': 'తీసేయండి', 'Subtotal': 'మొత్తం ధర', 'Proceed to checkout': 'చెకౌట్ చేయండి', 'items': 'వస్తువులు',
    'Shipping is calculated at checkout.': 'డెలివరీ ఖర్చు చెకౌట్‌లో కనిపిస్తుంది.',
    'Language': 'భాష', 'Shop crafts': 'కళాఖండాలు కొనండి', 'Sell with us': 'మాతో అమ్మండి',
    'Orders': 'ఆర్డర్లు', 'Cart': 'కార్ట్', 'Account': 'ఖాతా', 'Sign in': 'సైన్ ఇన్',
    'Sign out': 'సైన్ అవుట్', 'Seller workspace': 'విక్రేత కార్యస్థలం', 'Marketplace': 'మార్కెట్',
    'Administration': 'నిర్వహణ', 'Search crafts, materials, or artisans…': 'కళాఖండాలు, పదార్థాలు లేదా కళాకారులను వెతకండి…',
    'Search': 'వెతకండి', 'All crafts': 'అన్ని కళాఖండాలు', 'Handloom': 'చేనేత', 'Pottery': 'మట్టి కళ',
    'Woodcraft': 'చెక్క కళ', 'Metal art': 'లోహ కళ', 'Bamboo': 'వెదురు', 'Paintings': 'చిత్రాలు',
    'Made by hand. Chosen with heart.': 'చేతులతో తయారైంది. మనసుతో ఎంచుకున్నది.',
    'Discover the craft. Meet the maker.': 'కళను కనుగొనండి. కళాకారుడితో కలవండి.',
    'Thoughtful pieces, made by independent artisans. Explore textiles, pottery, and everyday objects with a story.': 'స్వతంత్ర కళాకారులు తయారుచేసిన ప్రత్యేక వస్తువులు. చేనేత, మట్టి కళ మరియు రోజువారీ వస్తువుల కథలను తెలుసుకోండి.',
    'Explore the collection': 'సేకరణ చూడండి', 'Start your artisan store': 'మీ కళల దుకాణం ప్రారంభించండి',
    'The craft collection': 'కళాఖండాల సేకరణ', 'Find something that feels like you.': 'మీ మనసుకు నచ్చినది ఎంచుకోండి.',
    'pieces to discover': 'వస్తువులు అందుబాటులో ఉన్నాయి', 'Filters': 'ఫిల్టర్లు', 'Clear filters': 'ఫిల్టర్లు తీసేయండి',
    'Sort by': 'క్రమం ఎంచుకోండి', 'Recommended': 'సూచించినవి', 'Price: low to high': 'ధర: తక్కువ నుండి ఎక్కువ',
    'Price: high to low': 'ధర: ఎక్కువ నుండి తక్కువ', 'Maximum price': 'గరిష్ఠ ధర',
    'No crafts found': 'కళాఖండాలు కనిపించలేదు', 'Try another search or clear your filters.': 'మరొక పదంతో వెతకండి లేదా ఫిల్టర్లు తీసేయండి.',
    'Loading the collection…': 'సేకరణ లోడ్ అవుతోంది…', 'Could not load the collection.': 'సేకరణ లోడ్ కాలేదు.',
    'Try again': 'మళ్లీ ప్రయత్నించండి', 'View product': 'ఉత్పత్తిని చూడండి', 'Add to cart': 'కార్ట్‌లో చేర్చండి',
    'Buy now': 'ఇప్పుడే కొనండి', 'Out of stock': 'స్టాక్ లేదు', 'Artisan craft': 'కళాకారుడి కళ',
    'GI certified': 'GI ధృవీకరించబడింది', 'Direct from the maker': 'నేరుగా కళాకారుడి నుండి', 'Your journey, your language': 'మీ ప్రయాణం, మీ భాష',
    'Shop and create listings in English, Hindi, or Telugu.': 'ఇంగ్లీష్, హిందీ లేదా తెలుగులో కొనండి, ఉత్పత్తులు చేర్చండి.',
    'CraftLink connects people with the hands behind the craft.': 'CraftLink మిమ్మల్ని కళను సృష్టించే కళాకారులతో కలుపుతుంది.',
    'Back to top': 'పైకి వెళ్లండి', 'Explore': 'చూడండి', 'For artisans': 'కళాకారుల కోసం', 'Your purchases': 'మీ కొనుగోళ్లు',
    'Create a store': 'దుకాణం సృష్టించండి', 'Track an order': 'ఆర్డర్ ట్రాక్ చేయండి', 'All rights reserved.': 'అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.',
    'Dashboard': 'డాష్‌బోర్డ్', 'AI Listing Studio': 'AI ఉత్పత్తి స్టూడియో', 'My Inventory': 'నా ఉత్పత్తులు',
    'Orders & Shipments': 'ఆర్డర్లు మరియు షిప్‌మెంట్లు', 'Payments & Payouts': 'చెల్లింపులు', 'Analytics': 'విశ్లేషణ',
    'Main Menu': 'ప్రధాన మెనూ', 'View Your Storefront': 'మీ మార్కెట్ చూడండి', 'Add Listing': 'ఉత్పత్తి చేర్చండి',
    'Your Store': 'మీ దుకాణం', 'Active Store Profile': 'ఎంచుకున్న దుకాణం', '+ Register New Store': '+ కొత్త దుకాణం సృష్టించండి',
    'Seller Dashboard': 'విక్రేత డాష్‌బోర్డ్', 'My Inventory & Catalog': 'నా ఉత్పత్తులు మరియు కేటలాగ్',
    'Analytics & Insights': 'విశ్లేషణ మరియు సమాచారం', 'Storefront': 'మార్కెట్', 'Open navigation': 'మెనూ తెరవండి',
    'Close navigation': 'మెనూ మూసివేయండి', 'Your creative workspace': 'మీ సృజనాత్మక కార్యస్థలం',
    'A photo. Your story. A listing ready to share.': 'ఒక ఫోటో. మీ కథ. అమ్మడానికి సిద్ధమైన ఉత్పత్తి.',
    'We guide you one step at a time. You can speak or type in your language.': 'ప్రతి దశలో మేము సహాయం చేస్తాం. మీరు మీ భాషలో మాట్లాడవచ్చు లేదా టైప్ చేయవచ్చు.',
    'Add Photo': 'ఫోటో చేర్చండి', 'Answer Questions': 'ప్రశ్నలకు జవాబులు', 'Check Details': 'వివరాలు చూడండి',
    'See Fair Price': 'సరైన ధర చూడండి', 'Send for Review': 'సమీక్షకు పంపండి',
    'AI cleans the image': 'AI ఫోటో శుభ్రం చేస్తుంది', 'One simple question at a time': 'ఒకేసారి ఒక సులభమైన ప్రశ్న',
    'Review your words': 'మీ సమాధానాలు చూడండి', 'Clear cost calculation': 'ఖర్చు స్పష్టమైన లెక్క', 'Final submission': 'చివరి దశ',
    'First, add one product photo': 'మొదట ఉత్పత్తి ఫోటో చేర్చండి', 'Do not worry about the background. AI will clean it.': 'బ్యాక్‌గ్రౌండ్ గురించి ఆందోళన వద్దు. AI శుభ్రం చేస్తుంది.',
    'Tap here and choose a photo': 'ఇక్కడ నొక్కి ఫోటో ఎంచుకోండి', 'JPG, PNG or WebP — up to 15MB': 'JPG, PNG లేదా WebP — గరిష్ఠంగా 15MB',
    'Your photo is ready': 'మీ ఫోటో సిద్ధంగా ఉంది', 'Next: Answer simple questions': 'తర్వాత: సులభమైన ప్రశ్నలకు జవాబులు',
    'Photo preview': 'ఫోటో ప్రివ్యూ', 'Your enhanced photo will appear here': 'మీ మెరుగైన ఫోటో ఇక్కడ కనిపిస్తుంది',
    'Choose a clear photo with the whole product visible.': 'ఉత్పత్తి మొత్తం కనిపించే స్పష్టమైన ఫోటో ఎంచుకోండి.',
    'Nothing is submitted until you review and confirm.': 'మీరు చూసి నిర్ధారించే వరకు ఉత్పత్తి పంపబడదు.',
    'Please wait. We are preparing the next step for you.': 'దయచేసి వేచి ఉండండి. మీ కోసం తదుపరి దశను సిద్ధం చేస్తున్నాం.',
    'Updating the question language…': 'ప్రశ్న భాషను మారుస్తున్నాం…', 'Check your product details': 'మీ ఉత్పత్తి వివరాలు చూడండి',
    'Nothing is submitted yet. Read the details below and use Edit if anything needs changing.': 'ఇంకా ఏమీ పంపలేదు. కింద వివరాలు చదవండి. మార్చడానికి సవరించండి నొక్కండి.',
    'Edit': 'సవరించండి', 'Save': 'సేవ్ చేయండి', 'Based only on your answers': 'మీ సమాధానాల ఆధారంగా',
    'Product details': 'ఉత్పత్తి వివరాలు', 'Details from your photo and answers': 'మీ ఫోటో మరియు సమాధానాల నుండి వివరాలు',
    'Your product story': 'మీ ఉత్పత్తి కథ', 'Listen': 'వినండి', 'Stop': 'ఆపండి',
  },
    // Seller workspace
    'My shop': 'నా దుకాణం',
    'My products': 'నా ఉత్పత్తులు',
    'Add a product': 'కొత్త ఉత్పత్తి చేర్చండి',
    'My money': 'నా సంపాదన',
    'How I am doing': 'నా పని ఎలా సాగుతోంది',
    'My shop details': 'దుకాణం వివరాలు',
    'Orders': 'ఆర్డర్లు',
    'Store': 'దుకాణం',
    'Business': 'వ్యాపారం',
    'Seller Central': 'విక్రేత కేంద్రం',
    'My shop today': 'ఈరోజు నా దుకాణం',
    'A quick look at what is happening': 'ఏం జరుగుతోందో ఒక్క చూపులో',
    'Add a new product': 'కొత్త ఉత్పత్తి చేర్చండి',
    'One photo, a few easy questions, and you are done': 'ఒక ఫోటో, కొన్ని సులభ ప్రశ్నలు, అంతే',
    'Everything you have put up for sale': 'మీరు అమ్మకానికి పెట్టినవన్నీ',
    'Confirm, pack and send what buyers ordered': 'ఆర్డర్లు నిర్ధారించి, ప్యాక్ చేసి పంపండి',
    'What you have earned and what is on the way': 'మీరు సంపాదించింది, రావలసింది',
    'What sells well, and what needs care': 'ఏది బాగా అమ్ముడవుతోంది, దేనిపై శ్రద్ధ కావాలి',
    'What buyers and our team can see': 'కొనుగోలుదారులు, మా బృందం చూసేవి',
    'View storefront': 'దుకాణం చూడండి',
    'Sign out': 'సైన్ అవుట్',
    'Refresh': 'రిఫ్రెష్',
    'Live': 'లైవ్',
    'updated': 'నవీకరించబడింది',
    'just now': 'ఇప్పుడే',
    'minute ago': 'నిమిషం క్రితం',
    'minutes ago': 'నిమిషాల క్రితం',
    'hour ago': 'గంట క్రితం',
    'hours ago': 'గంటల క్రితం',
    'day ago': 'రోజు క్రితం',
    'days ago': 'రోజుల క్రితం',
    'Good morning': 'శుభోదయం',
    'Good afternoon': 'నమస్కారం',
    'Good evening': 'శుభ సాయంత్రం',
    'You have': 'మీకు',
    'order to send today.': 'ఆర్డర్ ఈరోజు పంపాలి.',
    'orders to send today.': 'ఆర్డర్లు ఈరోజు పంపాలి.',
    'Everything is calm right now. Your shop is open and taking orders.': 'ప్రస్తుతం అంతా ప్రశాంతం. మీ దుకాణం తెరిచి ఉంది, ఆర్డర్లు తీసుకుంటోంది.',
    'Let us put your first product online today.': 'ఈరోజు మీ మొదటి ఉత్పత్తిని ఆన్‌లైన్‌లో పెడదాం.',
    'Listen to my summary': 'నా వివరాలు వినండి',
    'Money from sales': 'అమ్మకాల ద్వారా వచ్చినది',
    'Orders to send': 'పంపవలసిన ఆర్డర్లు',
    'Products on sale': 'అమ్మకంలో ఉన్న ఉత్పత్తులు',
    'Cash received': 'అందిన డబ్బు',
    'order': 'ఆర్డర్',
    'orders': 'ఆర్డర్లు',
    'piece': 'వస్తువు',
    'pieces': 'వస్తువులు',
    'New, confirmed or packed': 'కొత్తవి, నిర్ధారించినవి లేదా ప్యాక్ చేసినవి',
    'being checked': 'పరిశీలనలో',
    'to fix': 'సరిచేయాల్సినవి',
    'still on the way': 'ఇంకా రావలసినది',
    'What is happening': 'ఏం జరుగుతోంది',
    'Nothing yet today': 'ఈరోజు ఇంకా ఏమీ లేదు',
    'Orders and updates will appear here as they happen.': 'ఆర్డర్లు, అప్‌డేట్లు ఇక్కడ వెంటనే కనిపిస్తాయి.',
    'ordered': 'ఆర్డర్ చేశారు',
    'is live for buyers': 'ఇప్పుడు కొనుగోలుదారులకు అందుబాటులో ఉంది',
    'came back for changes': 'మార్పుల కోసం తిరిగి వచ్చింది',
    'is being checked by our team': 'మా బృందం పరిశీలిస్తోంది',
    'Needs your attention': 'మీ శ్రద్ధ కావాలి',
    'order is waiting for you': 'ఆర్డర్ మీ కోసం ఎదురుచూస్తోంది',
    'orders are waiting for you': 'ఆర్డర్లు మీ కోసం ఎదురుచూస్తున్నాయి',
    'Confirm, pack and send so buyers are not left waiting': 'నిర్ధారించి, ప్యాక్ చేసి పంపండి, కొనుగోలుదారులు ఎదురుచూడకూడదు',
    'product came back for changes': 'ఉత్పత్తి మార్పుల కోసం తిరిగి వచ్చింది',
    'Read the note from our team, fix it and send again': 'మా బృందం సందేశం చదివి, సరిచేసి మళ్లీ పంపండి',
    'product is almost sold out': 'ఉత్పత్తి దాదాపు అయిపోయింది',
    'Add more stock so buyers can keep ordering': 'స్టాక్ పెంచండి, ఆర్డర్లు కొనసాగుతాయి',
    'product is with our team for checking': 'ఉత్పత్తి పరిశీలన కోసం మా బృందం వద్ద ఉంది',
    'We usually finish checking within a working day': 'సాధారణంగా ఒక పని దినంలో పరిశీలన పూర్తవుతుంది',
    'Latest orders': 'తాజా ఆర్డర్లు',
    'See all': 'అన్నీ చూడండి',
    'Buyer': 'కొనుగోలుదారు',
    'Items': 'వస్తువులు',
    'Your share': 'మీ వాటా',
    'Status': 'స్థితి',
    'No orders yet': 'ఇంకా ఆర్డర్లు లేవు',
    'When someone buys one of your products, it will appear here straight away.': 'ఎవరైనా మీ ఉత్పత్తి కొన్న వెంటనే ఇక్కడ కనిపిస్తుంది.',
    'Tips that help you sell': 'అమ్మకాలు పెంచే చిట్కాలు',
    'Take the photo in daylight': 'పగటి వెలుతురులో ఫోటో తీయండి',
    'Near a window, on a plain cloth. Clear photos sell far more.': 'కిటికీ దగ్గర, సాదా వస్త్రంపై. స్పష్టమైన ఫోటోలు ఎక్కువ అమ్ముడవుతాయి.',
    'Tell the story of the piece': 'మీ వస్తువు కథ చెప్పండి',
    'Buyers love knowing how long it took and who made it.': 'ఎవరు, ఎంత సమయంలో చేశారో తెలుసుకోవడం కొనుగోలుదారులకు ఇష్టం.',
    'Send orders quickly': 'ఆర్డర్లు త్వరగా పంపండి',
    'Confirm the same day. Buyers remember sellers who are quick.': 'అదే రోజు నిర్ధారించండి. వేగవంతమైన విక్రేతలు గుర్తుండిపోతారు.',
    'Keep stock up to date': 'స్టాక్ సరిగ్గా ఉంచండి',
    'If a piece is sold out, update it so nobody is disappointed.': 'వస్తువు అయిపోతే నవీకరించండి, ఎవరూ నిరాశ చెందరు.',
    'Your very first order has arrived!': 'మీ మొట్టమొదటి ఆర్డర్ వచ్చింది!',
    'Confirm it today so the buyer knows their piece is on its way.': 'ఈరోజే నిర్ధారించండి, వస్తువు వస్తోందని కొనుగోలుదారుకు తెలుస్తుంది.',
    'Your shop is live for buyers': 'మీ దుకాణం కొనుగోలుదారులకు అందుబాటులోకి వచ్చింది',
    'Share your shop link with friends and customers. Orders will show up here the moment they arrive.': 'మీ దుకాణం లింక్‌ను స్నేహితులకు, ఖాతాదారులకు పంపండి. ఆర్డర్లు వచ్చిన వెంటనే ఇక్కడ కనిపిస్తాయి.',
    'Open orders': 'ఆర్డర్లు తెరవండి',
    'New order': 'కొత్త ఆర్డర్',
    'Welcome to CraftLink': 'CraftLink కు స్వాగతం',
    'Your shop is ready. Let us add your first product.': 'మీ దుకాణం సిద్ధం. మొదటి ఉత్పత్తిని చేర్చుదాం.',
    'Take one photo and answer a few easy questions by speaking or typing. We write the description and suggest a fair price. Nothing goes online until you say yes.': 'ఒక ఫోటో తీసి, మాట్లాడి లేదా టైప్ చేసి కొన్ని సులభ ప్రశ్నలకు జవాబు ఇవ్వండి. మేము వివరణ రాసి, సరైన ధర సూచిస్తాం. మీరు ఒప్పుకునే వరకు ఏదీ ఆన్‌లైన్‌లోకి వెళ్లదు.',
    'Add my first product': 'నా మొదటి ఉత్పత్తి చేర్చండి',
    'Take one photo': 'ఒక ఫోటో తీయండి',
    'Answer easy questions': 'సులభ ప్రశ్నలకు జవాబివ్వండి',
    'See a fair price': 'సరైన ధర చూడండి',
    'Send for checking': 'పరిశీలనకు పంపండి',
    'Sales': 'అమ్మకాలు',
    'in the last': 'గత',
    'days': 'రోజుల్లో',
    'Today': 'ఈరోజు',
    'Date range': 'కాల వ్యవధి',
    'No sales in this period yet. Share your shop link to get started.': 'ఈ కాలంలో ఇంకా అమ్మకాలు లేవు. మీ దుకాణం లింక్ పంచుకోండి.',
    'friend': 'మిత్రమా',
};

// Preserve context identity during development refreshes so existing consumers
// never momentarily read a different context from the refreshed provider.
const LanguageContext = import.meta.hot?.data.languageContext || createContext(null);
if (import.meta.hot) import.meta.hot.data.languageContext = LanguageContext;

export function LanguageProvider({ children }) {
  const [locale, setLocale] = useState(() => {
    try { return normalizeLocale(localStorage.getItem('craftlink_language') || 'en'); }
    catch { return 'en'; }
  });
  useEffect(() => {
    document.documentElement.lang = locale;
    try { localStorage.setItem('craftlink_language', locale); } catch { /* private browsing */ }
  }, [locale]);
  const language = LANGUAGE_OPTIONS.find(item => item.code === locale);
  const t = (key) => translations[locale]?.[key] || key;
  return (
    <LanguageContext.Provider value={{ locale, language, t, setLocale: value => setLocale(normalizeLocale(value)) }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
